import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

const gamesData = [
  {
    title: 'Grand Theft Auto V',
    description: 'Explorez le monde ouvert de Los Santos dans cette aventure criminelle épique. Jouez avec trois protagonistes uniques — Michael, Franklin et Trevor — et vivez une histoire immersive remplie d\'action, de conduite et de liberté totale dans un monde ouvert exceptionnel. Plus de 100 heures de gameplay avec le mode en ligne GTA Online inclus.',
    price: 15000,
    imageUrl: '/games/gta-v.png',
    downloadUrl: '/downloads/gta-v.zip',
    downloadLink: '',
    fileSize: '94.5 GB',
    version: '1.0.8',
    category: 'Action',
    developer: 'Rockstar Games',
    rating: 4.8,
    featured: true,
  },
  {
    title: 'Call of Duty: Modern Warfare III',
    description: 'Engagez-vous dans le conflit mondial le plus intense. Campagne solo captivante avec des missions en salle obscure, mode multijoueur compétitif avec 16 cartes mythiques remastérisées, et le fameux mode Zombies en monde ouvert. L\'expérience FPS la plus complète de la franchise.',
    price: 25000,
    imageUrl: '/games/cod-mw3.png',
    downloadUrl: '/downloads/cod-mw3.zip',
    downloadLink: '',
    fileSize: '78.5 GB',
    version: '1.0.3',
    category: 'Action',
    developer: 'Activision',
    rating: 4.3,
    featured: true,
  },
  {
    title: 'Halo Infinite',
    description: 'Le légendaire Master Chief revient dans sa plus grande aventure. Explorez un monde ouvert de science-fiction Zeta Halo, combattez les ennemis Banished avec de nouvelles armes et équipements, et découvrez le mystère du Halo. Mode multijoueur free-to-play inclus avec des saisons de contenu régulières.',
    price: 20000,
    imageUrl: '/games/halo-infinite.png',
    downloadUrl: '/downloads/halo-infinite.zip',
    downloadLink: '',
    fileSize: '52.8 GB',
    version: '1.0.5',
    category: 'Action',
    developer: '343 Industries',
    rating: 4.1,
    featured: false,
  },
  {
    title: 'Elden Ring',
    description: 'Un RPG en monde ouvert créé par Hidetaka Miyazaki et George R.R. Martin. Explorez les Terres Intermédiaires, affrontez des ennemis redoutables dans des combats exigeants et découvrez les secrets de l\'Anneau Elden. DLC Shadow of the Erdtree inclus. Plus de 150 boss uniques et un monde vaste à explorer.',
    price: 22000,
    imageUrl: '/games/elden-ring.png',
    downloadUrl: '/downloads/elden-ring.zip',
    downloadLink: '',
    fileSize: '48.3 GB',
    version: '1.0.2',
    category: 'RPG',
    developer: 'FromSoftware',
    rating: 4.9,
    featured: true,
  },
  {
    title: 'Cyberpunk 2077',
    description: 'Vivez dans la mégalopole de Night City, une ville obsédée par le pouvoir, le style et les modifications corporelles. Incarnez V, un mercenaire hors-la-loi à la recherche d\'un implant unique. DLC Phantom Liberty inclus avec Keanu Reeves. Plus de 100 heures de contenu avec des fins multiples.',
    price: 18000,
    imageUrl: '/games/cyberpunk-2077.png',
    downloadUrl: '/downloads/cyberpunk-2077.zip',
    downloadLink: '',
    fileSize: '65.1 GB',
    version: '2.1.0',
    category: 'RPG',
    developer: 'CD Projekt Red',
    rating: 4.5,
    featured: true,
  },
  {
    title: 'The Witcher 3: Wild Hunt',
    description: 'Incarnant le sorceleur Geralt de Riv, partez à la recherche de Ciri, poursuivie par la Chasse Sauvage. Un RPG à monde ouvert avec des quêtes mémorables et des choix moraux. Éditions complètes avec tous les DLC Blood and Wine et Hearts of Stone. Plus de 200 heures de contenu.',
    price: 12000,
    imageUrl: '/games/witcher-3.png',
    downloadUrl: '/downloads/witcher-3.zip',
    downloadLink: '',
    fileSize: '42.7 GB',
    version: '4.0.4',
    category: 'RPG',
    developer: 'CD Projekt Red',
    rating: 4.9,
    featured: false,
  },
  {
    title: 'EA Sports FC 24',
    description: 'Le football comme vous ne l\'avez jamais vu. Avec la technologie HyperMotion V et des licences exclusives, vivez le beau jeu dans le simulateur de football le plus réaliste. Modes Ultimate Team, Career Mode, Pro Clubs et VOLTA. Plus de 19 000 joueurs licenciés.',
    price: 20000,
    imageUrl: '/games/fc-24.png',
    downloadUrl: '/downloads/fc-24.zip',
    downloadLink: '',
    fileSize: '55.3 GB',
    version: '1.0.1',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 3.9,
    featured: true,
  },
  {
    title: 'NBA 2K24',
    description: 'Prenez le terrain avec les plus grandes stars du basket. Modes de jeu variés dont MyCareer, MyTeam et MyNBA, graphismes époustouflants et gameplay ultra-réaliste pour l\'expérience basket ultime. Saison NBA 2023-2024 complète avec tous les effectifs mis à jour.',
    price: 18000,
    imageUrl: '/games/nba-2k24.png',
    downloadUrl: '/downloads/nba-2k24.zip',
    downloadLink: '',
    fileSize: '62.4 GB',
    version: '1.0.0',
    category: 'Sport',
    developer: 'Visual Concepts',
    rating: 4.0,
    featured: false,
  },
  {
    title: 'Assassin\'s Creed Mirage',
    description: 'Retour aux sources de la franchise. Incarnez Basim dans le Bagdad du 9ème siècle. Infiltration, parkour et assassinats dans un monde ouvert magnifique et authentique. Un jeu plus compact et focalisé sur l\'essentiel de la série, avec un système de combat retravaillé.',
    price: 20000,
    imageUrl: '/games/ac-mirage.png',
    downloadUrl: '/downloads/ac-mirage.zip',
    downloadLink: '',
    fileSize: '38.9 GB',
    version: '1.0.6',
    category: 'Aventure',
    developer: 'Ubisoft',
    rating: 4.2,
    featured: true,
  },
  {
    title: 'God of War Ragnarök',
    description: 'Kratos et Atreus affrontent le Ragnarök dans cette suite épique. Combattez des dieux nordiques comme Thor et Odin, explorez les neuf royaumes et vivez une histoire émouvante père-fils. Système de combat amélioré avec de nouvelles armes et capacités runiques spectaculaires.',
    price: 22000,
    imageUrl: '/games/god-of-war-ragnarok.png',
    downloadUrl: '/downloads/god-of-war-ragnarok.zip',
    downloadLink: '',
    fileSize: '71.2 GB',
    version: '1.0.1',
    category: 'Aventure',
    developer: 'Santa Monica Studio',
    rating: 4.8,
    featured: true,
  },
  {
    title: 'Age of Empires IV',
    description: 'Bâtissez votre empire à travers les âges. Gérez vos ressources, construisez vos armées et dominez vos ennemis dans ce jeu de stratégie en temps réel référence. 14 civilisations jouables, campagnes historiques documentaires et mode multijoueur compétitif.',
    price: 15000,
    imageUrl: '/games/aoe-iv.png',
    downloadUrl: '/downloads/aoe-iv.zip',
    downloadLink: '',
    fileSize: '35.6 GB',
    version: '1.0.9',
    category: 'Stratégie',
    developer: 'Relic Entertainment',
    rating: 4.3,
    featured: false,
  },
  {
    title: 'Civilization VI',
    description: 'Conduisez votre civilisation de l\'Âge de Pierre à l\'Ère de l\'Information. Explorez, étendez vos territoires, développez votre culture et dominez le monde. Édition complète avec tous les DLC Gathering Storm et Rise and Fall. Plus de 50 civilisations jouables.',
    price: 12000,
    imageUrl: '/games/civ-vi.png',
    downloadUrl: '/downloads/civ-vi.zip',
    downloadLink: '',
    fileSize: '28.4 GB',
    version: '1.0.12',
    category: 'Stratégie',
    developer: 'Firaxis Games',
    rating: 4.6,
    featured: false,
  },
  {
    title: 'Red Dead Redemption 2',
    description: 'Vivez l\'histoire de Arthur Morgan et de la bande de Van der Linde dans l\'Amérique sauvage de 1899. Un chef-d\'œuvre de narration dans un monde ouvert époustouflant. Mode Red Dead Online inclus. Plus de 100 heures de contenu avec des graphismes photoréalistes.',
    price: 16000,
    imageUrl: '/games/rdr2.png',
    downloadUrl: '/downloads/rdr2.zip',
    downloadLink: '',
    fileSize: '82.5 GB',
    version: '1.0.4',
    category: 'Aventure',
    developer: 'Rockstar Games',
    rating: 4.9,
    featured: true,
  },
  {
    title: 'FIFA 24 Legacy Edition',
    description: 'Profitez du football avec les modes de jeu classiques. Gérez votre club en mode Carrière, jouez en ligne en mode Ultimate Team et revivez les plus grands moments du football mondial. Mises à jour des effectifs 2024 et ligues licenciées incluses.',
    price: 14000,
    imageUrl: '/games/fifa-24.png',
    downloadUrl: '/downloads/fifa-24.zip',
    downloadLink: '',
    fileSize: '48.7 GB',
    version: '1.0.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 3.5,
    featured: false,
  },
];

export async function GET() {
  try {
    const existingGames = await db.game.count();

    if (existingGames > 0) {
      return NextResponse.json({
        message: `${existingGames} jeux existent déjà`,
        count: existingGames,
      });
    }

    // Seed games
    const games = [];
    for (const gameData of gamesData) {
      const game = await db.game.create({
        data: gameData,
      });
      games.push(game);
    }

    return NextResponse.json({
      message: `${games.length} jeux ont été ajoutés avec succès`,
      count: games.length,
      games,
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Erreur lors du seed de la base de données' },
      { status: 500 }
    );
  }
}
