import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

const gamesData = [
  // ===== NARUTO STORM SERIES =====
  {
    title: 'Naruto: Ultimate Ninja Storm',
    description: 'Revivez les premières aventures de Naruto Uzumaki dans ce jeu de combat spectaculaire. Affrontez vos ennemis avec des combos dévastateurs et des jutsus spectaculaires en graphismes cel-shading. Explorez le village caché de Konoha et vivez l\'histoire du début de la série Naruto avec des combats épiques contre Zabuza, Haku et bien d\'autres.',
    price: 8000,
    imageUrl: '/games/naruto-storm-1.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '6.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.2,
    featured: false,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '8 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-6300',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 560 Ti / AMD Radeon HD 6870',
    recStorage: '8 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 2',
    description: 'Plongez dans la saga Shippuden avec Naruto et ses amis. Des combats dynamiques avec des QTE cinématiques spectaculaires, un mode histoire fidèle à l\'anime et un roster de personnages élargi. Affrontez l\'Akatsuki dans des batailles épiques et revivez les moments les plus emblématiques de la série jusqu\'à la rencontre avec Pain.',
    price: 10000,
    imageUrl: '/games/naruto-storm-2.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '8.2 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.5,
    featured: true,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '10 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-6300',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 560 Ti / AMD Radeon HD 6870',
    recStorage: '10 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 3',
    description: 'La guerre ninja fait rage ! Incarnez Naruto et les ninjas de toutes les nations dans la Grande Guerre Ninja. Combats de boss titanesques, un mode histoire riche avec des choix narratifs et plus de 80 personnages jouables. Les affrontements contre les Edo Kage et Obito Uchiha vous laisseront sans souffle.',
    price: 12000,
    imageUrl: '/games/naruto-storm-3.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '10.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.6,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 8',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '12 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '12 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 4',
    description: 'Le combat final de Naruto ! Découvrez la conclusion épique de la saga avec des combats à couper le souffle. Système de combat amélioré avec des changements de leader en plein combat, des jutsus combinés dévastateurs et la résolution du combat entre Naruto et Sasuke. Graphismes Next-Gen et plus de 100 personnages jouables.',
    price: 15000,
    imageUrl: '/games/naruto-storm-4.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '35.2 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.8,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-4160 / AMD Phenom II X4 805',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 470 / AMD Radeon HD 5850',
    minStorage: '40 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '40 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm Revolution',
    description: 'Un opus unique avec un scénario inédit créé par Masashi Kishimoto lui-même. Découvrez l\'histoire des fondateurs de l\'Akatsuki et affrontez des mechas géants Naruto. Nouveau système de combat avec les Ninja World Tournament et plus de 100 personnages dont des versions inédites.',
    price: 10000,
    imageUrl: '/games/naruto-storm-revolution.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '9.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.3,
    featured: false,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '12 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-6300',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 560 Ti / AMD Radeon HD 6870',
    recStorage: '12 Go SSD',
    recDirectX: 'Version 11',
  },

  // ===== DRAGON BALL SERIES =====
  {
    title: 'Dragon Ball Xenoverse',
    description: 'Créez votre propre guerrier et voyagez dans le temps pour corriger les anomalies de l\'histoire Dragon Ball. Personnalisez votre personnage parmi 5 races, apprenez des techniques iconiques et combattez aux côtés de Goku et ses amis. Mode multijoueur en ligne avec des batailles 3 contre 3 épiques.',
    price: 8000,
    imageUrl: '/games/db-xenoverse-1.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '9.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Dimps',
    rating: 4.0,
    featured: false,
    minOS: 'Windows Vista 64-bit / Windows 7',
    minCPU: 'Intel Core 2 Duo E8400 / AMD Phenom II X2 550',
    minRAM: '2 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '10 Go',
    minDirectX: 'Version 10',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i3-4160 / AMD FX-6300',
    recRAM: '4 Go',
    recGPU: 'NVIDIA GTX 560 / AMD Radeon HD 6870',
    recStorage: '10 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball Xenoverse 2',
    description: 'La suite améliorée avec un hub monde plus grand, Conton City. Plus de transformations, de techniques et de personnages. De nouveaux arcs narratifs incluant Dragon Ball Super avec Beerus, Golden Frieza et Goku Black. Système de combat affiné avec des mécaniques en ligne robustes et des raids de boss.',
    price: 12000,
    imageUrl: '/games/db-xenoverse-2.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '18.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Dimps',
    rating: 4.4,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-4160 / AMD FX-4130',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 470 / AMD Radeon HD 5850',
    minStorage: '20 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '20 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball FighterZ',
    description: 'Le jeu de combat compétition Dragon Ball par Arc System Works. Combats 3 contre 3 en 2.5D avec des graphismes anime époustouflants. Système de combat profond avec des combos techniques, des assists et des moves spectaculaires. Le jeu de combat Dragon Ball de référence pour l\'eSport et les tournois.',
    price: 15000,
    imageUrl: '/games/db-fighterz.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '4.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Arc System Works',
    rating: 4.7,
    featured: true,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i5-2450M / AMD FX-4100',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 650 / AMD Radeon HD 6870',
    minStorage: '6 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-3470 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '6 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball Z: Kakarot',
    description: 'Vivez l\'histoire complète de Dragon Ball Z comme jamais auparavant. Un RPG en monde ouvert où vous explorez le monde de Dragon Ball, pêchez, mangez, entraînez-vous et combattez. Revivez la saga Saiyan jusqu\'à la saga Buu avec des combats spectaculaires et une narration émotionnelle fidèle à l\'anime.',
    price: 18000,
    imageUrl: '/games/dbz-kakarot.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '30.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.5,
    featured: true,
    minOS: 'Windows 7 SP1 64-bit',
    minCPU: 'Intel Core i5-2400 / AMD Phenom II X6 1100T',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 750 Ti / AMD Radeon HD 7950',
    minStorage: '36 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 960 / AMD Radeon RX 470',
    recStorage: '36 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball: The Breakers',
    description: 'Un jeu multijoueur asymétrique unique dans l\'univers Dragon Ball. Incarnez un survivant ordinaire tentant d\'échapper à un Raider puissant (Cell, Frieza ou Buu) ou jouez le Raider et traquez les survivants. Coopération, stratégie et capacités spéciales pour survivre dans ce jeu de survie intense.',
    price: 10000,
    imageUrl: '/games/db-breakers.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '8.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Dimps',
    rating: 3.8,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-4460 / AMD FX-6300',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    minStorage: '10 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i5-6500 / AMD Ryzen 3 1200',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 960 / AMD RX 570',
    recStorage: '10 Go SSD',
    recDirectX: 'Version 11',
  },

  // ===== FIFA SERIES =====
  {
    title: 'FIFA 19',
    description: 'Vivez le football avec la licence UEFA Champions League exclusive. Le système de gameplay Active Touch offre un contrôle de balle plus réaliste, tandis que le mode Dynastie vous permet de suivre l\'histoire d\'Alex Hunter dans sa quête de gloire. Modes Ultimate Team, Career Mode et des ligues du monde entier.',
    price: 8000,
    imageUrl: '/games/fifa-19.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '40.2 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 4.0,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-2100 / AMD FX-4350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7850',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel i3-6300T / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 970 / AMD RX 580',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'FIFA 20',
    description: 'Découvrez VOLTA Football, le mode de jeu de rue qui ramène le football dans les rues. Créez votre personnage, personnalisez-le et jouez dans des terrains urbains du monde entier. Gameplay refiné avec le système de gestion de balle amélioré et des animations plus fluides pour une expérience footballistique authentique.',
    price: 10000,
    imageUrl: '/games/fifa-20.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '42.5 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 3.9,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-2100 / AMD FX-4350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7850',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel i3-6300T / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 970 / AMD RX 580',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'FIFA 21',
    description: 'Le football nouvelle génération avec des animations HyperMotion et un gameplay plus réaliste que jamais. Mode Carrière amélioré avec une gestion d\'équipe plus profonde, Ultimate Team avec de nouvelles façons de construire votre équipe et VOLTA avec encore plus de styles de jeu de rue.',
    price: 12000,
    imageUrl: '/games/fifa-21.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '45.8 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 3.8,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i3-2100 / AMD FX-4350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7850',
    minStorage: '50 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-3550 / AMD FX-8150',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 970 / AMD RX 580',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'FIFA 22',
    description: 'La technologie HyperMotion révolutionne le gameplay avec des captures de mouvement de matchs réels à 11 contre 11. Des milliers d\'animations nouvelles pour un réalisme inégalé. Mode Carrière avec création de club, Ultimate Team avec FUT Heroes et des ligues et coupes du monde entier.',
    price: 15000,
    imageUrl: '/games/fifa-22.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '48.3 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 4.1,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-6600K / AMD Ryzen 5 1600',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 570',
    minStorage: '50 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-6700K / AMD Ryzen 7 2700X',
    recRAM: '12 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 6700 XT',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'FIFA 23',
    description: 'Le dernier FIFA avec la Coupe du Monde Féminine et la licence UEFA Champions League. HyperMotion2 pour des animations encore plus réalistes, le mode de jeu à deux avec un ami et des améliorations de gameplay majeures. Cross-play entre plateformes pour la première fois dans la franchise.',
    price: 18000,
    imageUrl: '/games/fifa-23.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '52.1 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 4.3,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-6600K / AMD Ryzen 5 1600',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 570',
    minStorage: '100 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-6700K / AMD Ryzen 7 2700X',
    recRAM: '12 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 6700 XT',
    recStorage: '100 Go SSD',
    recDirectX: 'Version 12',
  },

  // ===== JEUX DE GUERRE =====
  {
    title: 'Call of Duty: Modern Warfare III',
    description: 'Engagez-vous dans le conflit mondial le plus intense. Campagne solo captivante avec des missions en salle obscure, mode multijoueur compétitif avec 16 cartes mythiques remastérisées, et le fameux mode Zombies en monde ouvert. L\'expérience FPS militaire la plus complète de la franchise avec des combats modernes réalistes.',
    price: 25000,
    imageUrl: '/games/cod-mw3.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '78.5 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'Activision',
    rating: 4.3,
    featured: true,
    minOS: 'Windows 10 64-bit (v1909 ou supérieur)',
    minCPU: 'Intel Core i5-6600 / AMD Ryzen 5 1400',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 960 / AMD RX 470',
    minStorage: '78 Go (SSD recommandé)',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11 64-bit',
    recCPU: 'Intel Core i7-6700K / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 5700 XT',
    recStorage: '78 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Call of Duty: Black Ops Cold War',
    description: 'Plongez dans la Guerre Froide avec des opérations secrètes à travers le monde. Campagne solo intense avec des choix narratifs, mode multijoueur classique Call of Duty et le mode Zombies avec des mécaniques de jeu innovantes. Opérations spéciales et intégration avec Call of Duty: Warzone.',
    price: 20000,
    imageUrl: '/games/cod-cold-war.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '82.3 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'Treyarch / Raven Software',
    rating: 4.1,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i3-4340 / AMD FX-6300',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 670 / AMD RX 470',
    minStorage: '50 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i5-2500K / AMD Ryzen 5 1600X',
    recRAM: '12 Go',
    recGPU: 'NVIDIA GTX 970 / AMD RX 580',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Battlefield V',
    description: 'Vivez la Seconde Guerre mondiale comme jamais. Des batailles multijoueur à 64 joueurs avec des véhicules, des destructions massives et le système Fortifications. Opérations Grandiose pour des campagnes multijoueur immersives et le mode Feu pour un Battle Royale tactique dans un cadre historique.',
    price: 12000,
    imageUrl: '/games/bf5.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '54.8 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'DICE',
    rating: 4.0,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i5-6600K / AMD FX-8350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 560',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 3 1300X',
    recRAM: '12 Go',
    recGPU: 'NVIDIA GTX 1060 6 Go / AMD RX 590',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Battlefield 2042',
    description: 'La guerre moderne à échelle massive avec des batailles à 128 joueurs. Spécialistes avec des capacités uniques, véhicules futuristes et des cartes gigantesques avec des événements dynamiques qui transforment le champ de bataille. Modes Conquête, Perforation et Danger Zone pour une guerre totale sans précédent.',
    price: 18000,
    imageUrl: '/games/bf2042.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '76.2 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'DICE',
    rating: 3.7,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-6600K / AMD Ryzen 5 1400',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 560',
    minStorage: '100 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 6600 XT',
    recStorage: '100 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Medal of Honor: Above and Beyond',
    description: 'Un jeu de guerre immersif en VR qui vous plonge au coeur de la Seconde Guerre mondiale. Incarnez un agent de l\'OSS à travers des missions en Europe occupée. Tirs réalistes, escouade d\'agents de la Résistance française et des témoignages de vétérans réels pour une expérience historique unique.',
    price: 15000,
    imageUrl: '/games/moh-ab.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '32.1 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'Respawn Entertainment',
    rating: 3.9,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i7-9700K / AMD Ryzen 7 2700X',
    minRAM: '16 Go',
    minGPU: 'NVIDIA RTX 2070 / AMD RX 5700 XT',
    minStorage: '40 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i9-9900K / AMD Ryzen 9 3900X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2080 Ti / AMD RX 6800 XT',
    recStorage: '40 Go SSD',
    recDirectX: 'Version 12',
  },

  // ===== JEUX DE COURSE =====
  {
    title: 'Need for Speed: Heat',
    description: 'Course de jour, drift de nuit. Dans Palm City, gagnez de l\'argent légalement en journée dans des Speedhunters Showdown, et montez en grade illégalement la nuit dans des courses underground. Personnalisez votre voiture avec des centaines de pièces et échappez à la police dans des poursuites intenses.',
    price: 12000,
    imageUrl: '/games/nfs-heat.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '28.5 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Ghost Games',
    rating: 4.1,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-3570 / AMD FX-6300',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 760 / AMD RX 560',
    minStorage: '30 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 3 1300X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA GTX 1060 6 Go / AMD RX 590',
    recStorage: '30 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Need for Speed: Unbound',
    description: 'Le style rencontre la vitesse. Un jeu de course avec un style visuel unique mêlant réalisme et effets graffiti animés. Participez à des courses qualificatives dans la semaine pour le grand rassemblement du week-end à Lakeshore. Customisez votre voiture avec des centaines de marqueurs visuels spectaculaires.',
    price: 18000,
    imageUrl: '/games/nfs-unbound.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '30.2 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Criterion Games',
    rating: 4.2,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-8600 / AMD Ryzen 5 2600',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 570',
    minStorage: '50 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-8700K / AMD Ryzen 5 3600X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 5700 XT',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Forza Horizon 5',
    description: 'Explorez le Mexique dans le jeu de course en monde ouvert le plus beau jamais créé. Des volcans aux jungles en passant par les plages et les villes, conduisez plus de 500 voitures dans des paysages à couper le souffle. Modes course, drift, drag, survie tempête et événements en ligne pour des heures de fun.',
    price: 20000,
    imageUrl: '/games/forza-horizon-5.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '103.6 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Playground Games',
    rating: 4.9,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-4460 / AMD Ryzen 3 1200',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 970 / AMD RX 470',
    minStorage: '110 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-9700K / AMD Ryzen 7 3700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2070 / AMD RX 5700 XT',
    recStorage: '110 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'F1 23',
    description: 'Prenez le volant d\'une Formule 1 dans le jeu officiel du championnat. Toutes les équipes, pilotes et circuits de la saison 2023. Mode Carrière amélioré avec la gestion d\'équipe, F1 World pour du contenu en ligne et le retour de Braking Point pour une histoire cinématique immersive.',
    price: 15000,
    imageUrl: '/games/f1-23.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '31.8 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Codemasters',
    rating: 4.3,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i3-2130 / AMD FX-4300',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 470',
    minStorage: '80 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i5-9600K / AMD Ryzen 5 2600X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA GTX 1660 Ti / AMD RX 590',
    recStorage: '80 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Assetto Corsa Competizione',
    description: 'Le simulateur de course GT le plus réaliste. Physique des pneus et de l\'aérodynamique ultra-précise, graphismes photoréalistes avec effet jour/nuit et météo dynamique. Championnat GT World Challenge officiel avec toutes les voitures et circuits. Le choix des pilotes virtuels exigeants.',
    price: 12000,
    imageUrl: '/games/acc.png',
    downloadUrl: '',
    downloadLink: '',
    fileSize: '18.4 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Kunos Simulazioni',
    rating: 4.6,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i5-4460 / AMD FX-8350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 770 / AMD RX 580',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-8700K / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 5700',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
];

export async function GET() {
  try {
    const existingGames = await db.game.count();

    if (existingGames > 0) {
      return NextResponse.json({
        message: `${existingGames} jeux existent déjà`,
        count: existingGames,
      });
    }

    // Seed games
    const games = [];
    for (const gameData of gamesData) {
      const game = await db.game.create({
        data: gameData,
      });
      games.push(game);
    }

    return NextResponse.json({
      message: `${games.length} jeux ont été ajoutés avec succès`,
      count: games.length,
      games,
    });
  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json(
      { error: 'Erreur lors du seed de la base de données' },
      { status: 500 }
    );
  }
}
