import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

// ===== GAMES DATA (used for auto-seed) =====
export const gamesData = [
  {
    title: 'Naruto X Boruto: Ultimate Ninja Storm Connections',
    description: 'La collection ultime Naruto Storm réunissant les personnages de Naruto et Boruto dans un jeu de combat spectaculaire. Découvrez un roster massif avec plus de 130 personnages jouables incluant les ninjas classiques et la nouvelle génération Boruto. Des combats dynamiques avec des jutsus dévastateurs, un mode histoire inédit qui relie les générations, et des graphismes sublimés. L\'expérience Ninja Storm la plus complète jamais créée.',
    price: 3500,
    imageUrl: '/games/naruto-boruto-connections.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1721906554-NARUTO.X.BORUTO.Ultimate.Ninja.STORM.CONNECTIONS.v1.40-P2P.torrent',
    fileSize: '29.5 GB',
    version: '1.40',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.5,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-2500K / AMD FX-8350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    minStorage: '35 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 5 2600',
    recRAM: '16 Go',
    recGPU: 'NVIDIA GTX 1060 / AMD RX 580',
    recStorage: '35 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 2',
    description: 'Plongez dans la saga Shippuden avec Naruto et ses amis. Des combats dynamiques avec des QTE cinématiques spectaculaires, un mode histoire fidèle à l\'anime et un roster de personnages élargi. Affrontez l\'Akatsuki dans des batailles épiques et revivez les moments les plus emblématiques de la série jusqu\'à la rencontre avec Pain.',
    price: 3500,
    imageUrl: '/games/naruto-storm-2.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1507600190-NARUTO.SHIPPUDEN.Ultimate.Ninja.STORM.2-CODEX.WwW.GamesTorrents.CoM.torrent',
    fileSize: '8.2 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.5,
    featured: true,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '10 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-6300',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 560 Ti / AMD Radeon HD 6870',
    recStorage: '10 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 3',
    description: 'La guerre ninja fait rage ! Incarnez Naruto et les ninjas de toutes les nations dans la Grande Guerre Ninja. Combats de boss titanesques, un mode histoire riche avec des choix narratifs et plus de 80 personnages jouables. Les affrontements contre les Edo Kage et Obito Uchiha vous laisseront sans souffle.',
    price: 3500,
    imageUrl: '/games/naruto-storm-3.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/Naruto-Shippuden-Ultimate-Ninja-Storm-3-Full-Burst-[MULTI6][PROPHET]-(Torrent).torrent',
    fileSize: '10.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.6,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 8',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '12 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '12 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm 4',
    description: 'Le combat final de Naruto ! Découvrez la conclusion épique de la saga avec des combats à couper le souffle. Système de combat amélioré avec des changements de leader en plein combat, des jutsus combinés dévastateurs et la résolution du combat entre Naruto et Sasuke. Graphismes Next-Gen et plus de 100 personnages jouables.',
    price: 3500,
    imageUrl: '/games/naruto-storm-4.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/NARUTO.SHIPPUDEN.Ultimate.Ninja_.STORM_.4.Road_.to_.Boruto.DLC-CODEX.torrent',
    fileSize: '35.2 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.8,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-4160 / AMD Phenom II X4 805',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 470 / AMD Radeon HD 5850',
    minStorage: '40 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '40 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Naruto Shippuden: Ultimate Ninja Storm Revolution',
    description: 'Un opus unique avec un scénario inédit créé par Masashi Kishimoto lui-même. Découvrez l\'histoire des fondateurs de l\'Akatsuki et affrontez des mechas géants Naruto. Nouveau système de combat avec les Ninja World Tournament et plus de 100 personnages dont des versions inédites.',
    price: 3500,
    imageUrl: '/games/naruto-storm-revolution.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1512241698-Naruto.Shippuden.Ultimate.Ninja.Storm.Revolution.MULTI-PROPHET.WwW.GamesTorrents.CoM.torrent',
    fileSize: '9.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.3,
    featured: false,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i3-530 / AMD Phenom II X2 550',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '12 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-2500K / AMD FX-6300',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 560 Ti / AMD Radeon HD 6870',
    recStorage: '12 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball Xenoverse',
    description: 'Créez votre propre guerrier et voyagez dans le temps pour corriger les anomalies de l\'histoire Dragon Ball. Personnalisez votre personnage parmi 5 races, apprenez des techniques iconiques et combattez aux côtés de Goku et ses amis. Mode multijoueur en ligne avec des batailles 3 contre 3 épiques.',
    price: 3500,
    imageUrl: '/games/db-xenoverse-1.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/Dragonball-Xenoverse-[MULTI8][CODEX]-(Torrent).torrent',
    fileSize: '9.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Dimps',
    rating: 4.0,
    featured: false,
    minOS: 'Windows Vista 64-bit / Windows 7',
    minCPU: 'Intel Core 2 Duo E8400 / AMD Phenom II X2 550',
    minRAM: '2 Go',
    minGPU: 'NVIDIA GTX 260 / AMD Radeon HD 5770',
    minStorage: '10 Go',
    minDirectX: 'Version 10',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i3-4160 / AMD FX-6300',
    recRAM: '4 Go',
    recGPU: 'NVIDIA GTX 560 / AMD Radeon HD 6870',
    recStorage: '10 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball Xenoverse 2',
    description: 'La suite améliorée avec un hub monde plus grand, Conton City. Plus de transformations, de techniques et de personnages. De nouveaux arcs narratifs incluant Dragon Ball Super avec Beerus, Golden Frieza et Goku Black. Système de combat affiné avec des mécaniques en ligne robustes et des raids de boss.',
    price: 3500,
    imageUrl: '/games/db-xenoverse-2.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1507785660-Dragon.ball.xenoverse.2-CODEX.WwW.GamesTorrents.CoM.torrent',
    fileSize: '18.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Dimps',
    rating: 4.4,
    featured: true,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-4160 / AMD FX-4130',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 470 / AMD Radeon HD 5850',
    minStorage: '20 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '20 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball FighterZ',
    description: 'Le jeu de combat compétition Dragon Ball par Arc System Works. Combats 3 contre 3 en 2.5D avec des graphismes anime époustouflants. Système de combat profond avec des combos techniques, des assists et des moves spectaculaires. Le jeu de combat Dragon Ball de référence pour l\'eSport et les tournois.',
    price: 3500,
    imageUrl: '/games/db-fighterz.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1552396786-Dragon Ball FighterZ Ultimate Edition [wWw.GamesTorrents.TV].torrent',
    fileSize: '4.8 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Arc System Works',
    rating: 4.7,
    featured: true,
    minOS: 'Windows 7 64-bit',
    minCPU: 'Intel Core i5-2450M / AMD FX-4100',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 650 / AMD Radeon HD 6870',
    minStorage: '6 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-3470 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7870',
    recStorage: '6 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball Z: Kakarot',
    description: 'Vivez l\'histoire complète de Dragon Ball Z comme jamais auparavant. Un RPG en monde ouvert où vous explorez le monde de Dragon Ball, pêchez, mangez, entraînez-vous et combattez. Revivez la saga Saiyan jusqu\'à la saga Buu avec des combats spectaculaires et une narration émotionnelle fidèle à l\'anime.',
    price: 3500,
    imageUrl: '/games/dbz-kakarot.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1692362445-Dragon.Ball.Z.Kakarot.23rd.World.Tournament-RUNE.torrent',
    fileSize: '30.5 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'CyberConnect2',
    rating: 4.5,
    featured: true,
    minOS: 'Windows 7 SP1 64-bit',
    minCPU: 'Intel Core i5-2400 / AMD Phenom II X6 1100T',
    minRAM: '4 Go',
    minGPU: 'NVIDIA GTX 750 Ti / AMD Radeon HD 7950',
    minStorage: '36 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i5-4460 / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 960 / AMD Radeon RX 470',
    recStorage: '36 Go SSD',
    recDirectX: 'Version 11',
  },
  {
    title: 'Dragon Ball: Sparking! ZERO',
    description: 'Le retour tant attendu de la série Budokai Tenkaichi ! Après plus de 15 ans d\'attente, Dragon Ball: Sparking! ZERO propose des combats spectaculaires en 3D avec des graphismes next-gen. Plus de 180 personnages jouables incluant Dragon Ball Super, des arènes destructibles, des transformations en plein combat et un mode histoire complet couvrant la saga Dragon Ball Z et Super. Le jeu de combat Dragon Ball ultime.',
    price: 3500,
    imageUrl: '/games/db-sparking-zero.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1770991591-Dragon.Ball.Sparking.ZERO.v20260206-P2P.torrent',
    fileSize: '28.6 GB',
    version: '1.0',
    category: 'Combat',
    developer: 'Spike Chunsoft',
    rating: 4.8,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-9600K / AMD Ryzen 5 2600',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 970 / AMD RX 570',
    minStorage: '40 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-9700K / AMD Ryzen 7 3700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2070 / AMD RX 5700 XT',
    recStorage: '40 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'FIFA 19',
    description: 'Vivez le football avec la licence UEFA Champions League exclusive. Le système de gameplay Active Touch offre un contrôle de balle plus réaliste, tandis que le mode Dynastie vous permet de suivre l\'histoire d\'Alex Hunter dans sa quête de gloire. Modes Ultimate Team, Career Mode et des ligues du monde entier.',
    price: 3500,
    imageUrl: '/games/fifa-19.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1552345876-Fifa 2019 [wWw.GamesTorrents.TV].torrent',
    fileSize: '40.2 GB',
    version: '1.0',
    category: 'Sport',
    developer: 'EA Sports',
    rating: 4.0,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i3-2100 / AMD FX-4350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 660 / AMD Radeon HD 7850',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel i3-6300T / AMD FX-8350',
    recRAM: '8 Go',
    recGPU: 'NVIDIA GTX 970 / AMD RX 580',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Call of Duty: Modern Warfare III',
    description: 'Engagez-vous dans le conflit mondial le plus intense. Campagne solo captivante avec des missions en salle obscure, mode multijoueur compétitif avec 16 cartes mythiques remastérisées, et le fameux mode Zombies en monde ouvert. L\'expérience FPS militaire la plus complète de la franchise avec des combats modernes réalistes.',
    price: 3500,
    imageUrl: '/games/cod-mw3.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1755089803-Call.of.Duty.Modern.Warfare.III.v10.4-P2P.torrent',
    fileSize: '78.5 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'Activision',
    rating: 4.3,
    featured: true,
    minOS: 'Windows 10 64-bit (v1909 ou supérieur)',
    minCPU: 'Intel Core i5-6600 / AMD Ryzen 5 1400',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 960 / AMD RX 470',
    minStorage: '78 Go (SSD recommandé)',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11 64-bit',
    recCPU: 'Intel Core i7-6700K / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 5700 XT',
    recStorage: '78 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Battlefield V',
    description: 'Vivez la Seconde Guerre mondiale comme jamais. Des batailles multijoueur à 64 joueurs avec des véhicules, des destructions massives et le système Fortifications. Opérations Grandiose pour des campagnes multijoueur immersives et le mode Feu pour un Battle Royale tactique dans un cadre historique.',
    price: 3500,
    imageUrl: '/games/bf5.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1552352842-Battlefield V Deluxe Edition [wWw.GamesTorrents.TV].torrent',
    fileSize: '54.8 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'DICE',
    rating: 4.0,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i5-6600K / AMD FX-8350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 560',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 3 1300X',
    recRAM: '12 Go',
    recGPU: 'NVIDIA GTX 1060 6 Go / AMD RX 590',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Battlefield 2042',
    description: 'La guerre moderne à échelle massive avec des batailles à 128 joueurs. Spécialistes avec des capacités uniques, véhicules futuristes et des cartes gigantesques avec des événements dynamiques qui transforment le champ de bataille. Modes Conquête, Perforation et Danger Zone pour une guerre totale sans précédent.',
    price: 3500,
    imageUrl: '/games/bf2042.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1646578966-Bigfield.2042-DARKSiDERS.torrent',
    fileSize: '76.2 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'DICE',
    rating: 3.7,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-6600K / AMD Ryzen 5 1400',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 1050 Ti / AMD RX 560',
    minStorage: '100 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 6600 XT',
    recStorage: '100 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Medal of Honor: Above and Beyond',
    description: 'Un jeu de guerre immersif en VR qui vous plonge au coeur de la Seconde Guerre mondiale. Incarnez un agent de l\'OSS à travers des missions en Europe occupée. Tirs réalistes, escouade d\'agents de la Résistance française et des témoignages de vétérans réels pour une expérience historique unique.',
    price: 3500,
    imageUrl: '/games/moh-ab.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1624798068-Medal.of.Honor.Above.and.Beyond.VR-VREX.torrent',
    fileSize: '32.1 GB',
    version: '1.0',
    category: 'Guerre',
    developer: 'Respawn Entertainment',
    rating: 3.9,
    featured: false,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i7-9700K / AMD Ryzen 7 2700X',
    minRAM: '16 Go',
    minGPU: 'NVIDIA RTX 2070 / AMD RX 5700 XT',
    minStorage: '40 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i9-9900K / AMD Ryzen 9 3900X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2080 Ti / AMD RX 6800 XT',
    recStorage: '40 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Need for Speed: Heat',
    description: 'Course de jour, drift de nuit. Dans Palm City, gagnez de l\'argent légalement en journée dans des Speedhunters Showdown, et montez en grade illégalement la nuit dans des courses underground. Personnalisez votre voiture avec des centaines de pièces et échappez à la police dans des poursuites intenses.',
    price: 3500,
    imageUrl: '/games/nfs-heat.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1585200417-Need for Speed Heat [wWw.GamesTorrents.NU].torrent',
    fileSize: '28.5 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Ghost Games',
    rating: 4.1,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-3570 / AMD FX-6300',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 760 / AMD RX 560',
    minStorage: '30 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-4790 / AMD Ryzen 3 1300X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA GTX 1060 6 Go / AMD RX 590',
    recStorage: '30 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Forza Horizon 5',
    description: 'Explorez le Mexique dans le jeu de course en monde ouvert le plus beau jamais créé. Des volcans aux jungles en passant par les plages et les villes, conduisez plus de 500 voitures dans des paysages à couper le souffle. Modes course, drift, drag, survie tempête et événements en ligne pour des heures de fun.',
    price: 3500,
    imageUrl: '/games/forza-horizon-5.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1638621758-Forza.Horizon.5.Premium.Edition.v1.414.967.0-P2P.torrent',
    fileSize: '103.6 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Playground Games',
    rating: 4.9,
    featured: true,
    minOS: 'Windows 10 64-bit',
    minCPU: 'Intel Core i5-4460 / AMD Ryzen 3 1200',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 970 / AMD RX 470',
    minStorage: '110 Go',
    minDirectX: 'Version 12',
    recOS: 'Windows 10 64-bit / Windows 11',
    recCPU: 'Intel Core i7-9700K / AMD Ryzen 7 3700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2070 / AMD RX 5700 XT',
    recStorage: '110 Go SSD',
    recDirectX: 'Version 12',
  },
  {
    title: 'Assetto Corsa Competizione',
    description: 'Le simulateur de course GT le plus réaliste. Physique des pneus et de l\'aérodynamique ultra-précise, graphismes photoréalistes avec effet jour/nuit et météo dynamique. Championnat GT World Challenge officiel avec toutes les voitures et circuits. Le choix des pilotes virtuels exigeants.',
    price: 3500,
    imageUrl: '/games/acc.png',
    downloadUrl: '',
    downloadLink: 'https://www.gamestorrents.app/wp-content/uploads/files/1761393701-Assetto.Corsa.Competizione.v1.10.3-P2P.torrent',
    fileSize: '18.4 GB',
    version: '1.0',
    category: 'Course',
    developer: 'Kunos Simulazioni',
    rating: 4.6,
    featured: false,
    minOS: 'Windows 7 64-bit / Windows 10',
    minCPU: 'Intel Core i5-4460 / AMD FX-8350',
    minRAM: '8 Go',
    minGPU: 'NVIDIA GTX 770 / AMD RX 580',
    minStorage: '50 Go',
    minDirectX: 'Version 11',
    recOS: 'Windows 10 64-bit',
    recCPU: 'Intel Core i7-8700K / AMD Ryzen 7 2700X',
    recRAM: '16 Go',
    recGPU: 'NVIDIA RTX 2060 / AMD RX 5700',
    recStorage: '50 Go SSD',
    recDirectX: 'Version 12',
  },
];

// Auto-seed: ensure games exist in DB before returning
async function ensureGamesSeeded() {
  try {
    const count = await db.game.count();
    if (count === 0) {
      console.log('No games found, auto-seeding...');
      for (const gameData of gamesData) {
        await db.game.create({ data: gameData });
      }
      console.log(`Auto-seeded ${gamesData.length} games`);
    }
  } catch (error) {
    console.error('Auto-seed error:', error);
  }
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const category = searchParams.get('category');
  const search = searchParams.get('search');

  try {
    // Auto-seed if DB is empty
    await ensureGamesSeeded();

    const where: Record<string, unknown> = {};

    if (category && category !== 'Tous') {
      where.category = category;
    }

    if (search) {
      where.title = {
        contains: search,
      };
    }

    const games = await db.game.findMany({
      where,
      orderBy: { createdAt: 'desc' },
    });

    return NextResponse.json(games);
  } catch (error) {
    console.error('Get games error:', error);
    return NextResponse.json(
      { error: 'Erreur lors du chargement des jeux' },
      { status: 500 }
    );
  }
}
